### ISSUE TITLE
Telogator error

### ISSUE THREAD

**Issue by tbenavi1** [zstephens/telogator#10]
Hello, I get the following error trying to run telogator.
```
using default telomere kmers
getting all read data from input alignment... (28 sec)
initial read filtering... (21 sec)
 - 65686 --> 649 reads
identify anchorable telomeres... (2 sec)
 - 649 --> 178 reads

reads filtered:
 - min_readlen 18002
 - min_telbases 30731
 - no_anchored_tel 469
 - pq_mix 1
 - trim_filter 38
 - unexplained_seq 1
 - unknown_ref 16266

removing anchored tels that double-anchored according to other reads... (0 sec)
 - 178 --> 148 reads
 - removing reads with tel regions that are insufficiently canonical...
 - Traceback (most recent call last):
  File "/home/rranallo-benavidez/software/telogator/telogator.py", line 523, in <module>
    main()
  File "/home/rranallo-benavidez/software/telogator/telogator.py", line 394, in main
    del_keys     = get_tels_below_canonical_thresh(ANCHORED_TEL_BY_CHR, gtbct_params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rranallo-benavidez/software/telogator/source/tg_tel.py", line 403, in get_tels_below_canonical_thresh
    my_canonical_frac = get_telomere_base_count(my_telseq, [CANONICAL_STRING, CANONICAL_STRING_REV], mode=READ_TYPE) / float(len(my_telseq))
                                                ^^^^^^^^^
UnboundLocalError: cannot access local variable 'my_telseq' where it is not associated with a value
 ```
I tried to track it down and realized that the problem is in lines 392-401 in tg_tel.py. Specifically, if the variable k does not end in p or q then my_telseq is not defined. I printed out ANCHORED_TEL_BY_CHR at this point and saw that the first k is "chr1" which doesn't end in p or q. I didn't debug any further. I was wondering if you had any insights. Thanks for any assistance.

**Comment by tbenavi1** [comment]
Ah, I figured out my problem. In the winnowmap step I didn't align to the correct genome. I realize I needed to align to the t2t-telogator-ref.fa in the resources directory. Thanks.

**Comment by zstephens** [comment]
Greetings, was the input bam aligned to resource/t2t-telogator-ref.fa?

**Comment by tbenavi1** [comment]
That was my error. oops.

**Comment by zstephens** [comment]
Oh. you got to it before me heh. Let me know if you run into any other problems!
